Write output to XDG dir and write XML for GNOME
Kharacternyk/pacwall pull request #13
Opened 2020-03-24 18:40 UTC by ChiDal

KDE searches for walls in `$HOME/.local/share/wallpapers` ([see this](https://forum.kde.org/viewtopic.php?t=135265)). Since this is an XDG dir, I suppose WMs also look here if they have a setting. I created another copy function for readability. Also please check line 100

2020-03-24 19:16 UTC, Kharacternyk requested changes

2020-03-24 19:16 UTC, Kharacternyk commented on pacwall.sh
> +        #This will make the wallpapers visible in KDE settings (and maybe WMs if they have a setting)
We need to add `mkdir -p ~/.local/share/wallpapers/pacwall`. I get `cp: cannot create regular file '/home/nazar/.local/share/wallpapers/pacwall/pacwalldarkslategray.png': No such file or directory` without this.

2020-03-24 19:16 UTC, Kharacternyk commented on pacwall.sh
> +        copy_to_xdg
If we aren't on GNOME, we don't resize the image. This means that `copy_to_xdg` makes sense only on GNOME.

2020-03-24 19:16 UTC, Kharacternyk commented on pacwall.sh
> +    set +e
Could you remove the whitespace?

2020-03-24 19:24 UTC, ChiDal commented on pacwall.sh
> +        #This will make the wallpapers visible in KDE settings (and maybe WMs if they have a setting)
Oh yeah totally forgot

2020-03-24 19:25 UTC, ChiDal commented on pacwall.sh
> +        copy_to_xdg
```suggestion
        -copy_to_xdg
```

2020-03-24 19:25 UTC, ChiDal commented on pacwall.sh
> +        copy_to_xdg
```suggestion
```

2020-03-24 19:25 UTC, ChiDal commented on pacwall.sh
> +    set +e
```suggestion
    set +e
```

2020-03-24 19:26 UTC, ChiDal commented on pacwall.sh
> +        #This will make the wallpapers visible in KDE settings (and maybe WMs if they have a setting)
```suggestion
        #This will make the wallpapers visible in KDE settings (and maybe WMs if they have a setting)
        mkdir -p ~/.local/share/wallpapers/pacwall
```

2020-03-24 19:27 UTC, ChiDal commented
I love this suggestion functionality

2020-03-24 19:34 UTC, ChiDal commented
Please check this now

2020-03-24 19:34 UTC, Kharacternyk commented on pacwall.sh
> +XDGOUT="$HOME/.local/share/wallpapers/pacwall/pacwall${BACKGROUND}.png"
If a user overrides background using `-b` flag, the `XDGOUT` doesn't change. When I run `./pacwall.sh -b gold` the `XDGOUT` is still `.../pacwalldarkslategray.pnn` and `feh` uses the wrong wallpaper.

2020-03-24 19:36 UTC, ChiDal commented on pacwall.sh
> +XDGOUT="$HOME/.local/share/wallpapers/pacwall/pacwall${BACKGROUND}.png"
That's why I put the copy_to_xdg line in the `else` part

2020-03-24 19:37 UTC, ChiDal commented on pacwall.sh
> +XDGOUT="$HOME/.local/share/wallpapers/pacwall/pacwall${BACKGROUND}.png"
Oh no my mistake sorry

2020-03-24 19:39 UTC, ChiDal commented on pacwall.sh
> +XDGOUT="$HOME/.local/share/wallpapers/pacwall/pacwall${BACKGROUND}.png"
Where should we define XDGOUT?

2020-03-24 19:43 UTC, Kharacternyk commented on pacwall.sh
> +XDGOUT="$HOME/.local/share/wallpapers/pacwall/pacwall${BACKGROUND}.png"
I guess we should define it at the end of the script, when all cmdoptions have been parsed.

2020-03-24 19:51 UTC, ChiDal commented on pacwall.sh
> +XDGOUT="$HOME/.local/share/wallpapers/pacwall/pacwall${BACKGROUND}.png"
ok

2020-03-24 20:00 UTC, Kharacternyk commented on pacwall.sh
> +        hsetroot -solid $BACKGROUND -full "${XDGOUT}" \
Since we don't copy to `XDGOUT` when not on GNOME anymore, we shouldn't change the paths.

2020-03-24 20:11 UTC, ChiDal commented
Merge conflicts resolved, writing this comment from KDE. The wall shows up

2020-03-24 20:14 UTC, Kharacternyk commented
See my comment above. It doesn't work on my machine because of the wrong path.

2020-03-24 20:21 UTC, ChiDal commented
We should copy to XDGOUT in case of KDE though.

2020-03-24 20:26 UTC, Kharacternyk commented
Then we should either:

- Bring back `copy_to_xdg` invocation. The wallpapers there will be unresized though.
- Check for KDE Plasma just like for GNOME using `DESKTOP_SESSION`.

What do you think?

2020-03-24 20:29 UTC, ChiDal commented
Copy the resized wall to XDGOUT?

2020-03-24 20:30 UTC, Kharacternyk commented
`imagemagick` would be a strict dependency then, I don't like it.

2020-03-24 20:33 UTC, ChiDal commented
Briefly, why is imagemagick needed in GNOME?

2020-03-24 20:35 UTC, Kharacternyk commented
Because of #14. GNOME can't be told to center the image and use a solid color outside, GNOME just stretches the image.

2020-03-24 20:37 UTC, ChiDal commented
I guess check for KDE then. I just uninstalled kde, else i would tell you the output of `$DESKTOP SESSION`

2020-03-24 20:42 UTC, Kharacternyk commented
I think now that just copying to `.local/share/...` is better. There are a lot of DEs that may use this path. Can you revert my change about removing `copy_to_xdg` invocation?

2020-03-24 20:43 UTC, ChiDal commented
I guess you should make a post on r/archlinux or r/kde, they'll tell you. Also you'll get testers

2020-03-24 20:44 UTC, Kharacternyk commented
Tell me what?

2020-03-24 20:47 UTC, ChiDal commented
Done

2020-03-24 20:49 UTC, ChiDal commented
So in case of GNOME, non-imagemagick walls go to XDGOUT and just twopi in other cases?

2020-03-24 20:49 UTC, merged

2020-03-24 20:51 UTC, Kharacternyk commented
Yes.

2020-03-25 03:32 UTC, ChiDal commented
Oof I just thought of this: if someone using a non-GNOME DE uses the settings GUI to change their wallpaper, it'll be unresized

2020-03-25 04:58 UTC, ChiDal commented
Time to reopen #14?

2020-03-25 11:36 UTC, Kharacternyk commented
We'll track it in #16.